# Generated by Django 5.1.7 on 2025-03-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_position', models.CharField(max_length=100)),
                ('moderator_shedule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NorthernWarmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nw_name', models.CharField(max_length=30)),
                ('nw_join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrant_name', models.CharField(max_length=30)),
                ('birthday_date', models.DateField()),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.moderators')),
            ],
        ),
        migrations.CreateModel(
            name='NWAArchiveArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_art', models.CharField(max_length=100)),
                ('work_publication_date', models.DateField()),
                ('work_type', models.IntegerField()),
                ('blog_part', models.IntegerField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.blogs')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.northernwarmers')),
            ],
        ),
        migrations.CreateModel(
            name='NWAArchiveCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_code', models.CharField(max_length=100)),
                ('work_publication_date', models.DateField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.blogs')),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.moderators')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.northernwarmers')),
            ],
        ),
        migrations.CreateModel(
            name='NWAArchiveCongratulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congratulation_text', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=30)),
                ('work_publication_date', models.DateField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.blogs')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.northernwarmers')),
            ],
        ),
        migrations.CreateModel(
            name='NWAArchiveTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_text', models.TextField()),
                ('work_publication_date', models.DateField()),
                ('work_type', models.IntegerField()),
                ('blog_part', models.IntegerField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.blogs')),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.moderators')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.northernwarmers')),
            ],
        ),
    ]
