# Generated by Django 3.2.25 on 2025-05-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWA_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderators',
            name='nw_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NWA_archive.northernwarmers'),
        ),
        migrations.AddField(
            model_name='northernwarmers',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
