# Generated by Django 3.2.25 on 2025-03-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('shedule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='northern_warmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.IntegerField()),
                ('blog_part', models.IntegerField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.blogs')),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.moderators')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.northern_warmers')),
            ],
        ),
        migrations.CreateModel(
            name='congratulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.blogs')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.northern_warmers')),
            ],
        ),
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.blogs')),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.moderators')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.northern_warmers')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='boss_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.moderators'),
        ),
        migrations.CreateModel(
            name='arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.IntegerField()),
                ('blog_part', models.IntegerField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.blogs')),
                ('nw_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.northern_warmers')),
            ],
        ),
    ]
